language: elixir
elixir: 1.11
otp_release:
  - 23.0
sudo: false
before_script:
  - mix deps.get
  - mix deps.update certifi
env:
  - MIX_ENV=test
script:
  - mix coveralls.travis --umbrella --include remote
services:
  - redis-server
